var OrganizationsNew = [
    {
        "manager": "",
        "addTime": "2023-11-13 17:49:13",
        "subs": [
            {
                "manager": "",
                "addTime": "2023-12-01 14:55:45",
                "subs": [
                    {
                        "isDefaultAuth": 1,
                        "uId": 75005,
                        "jobId": "GRT00004",
                        "name": "测试04",
                        "jobIdName": "GRT00004(测试04)",
                        "isDepManager": 0,
                        "orgId": 41,
                    }
                ],
                "level": "一级部门",
                "parentIds": "41-44-",
                "addJob": "GRT26227(柯柯)",
                "updateTime": "2023-12-01 14:55:45",
                "type": 10,
                "parentId": 41,
                "companyId": 41,
                "name": "总经办",
                "id": 44,
                "orgNums": 1,
                "managers": "",
                "status": 1,
                "area_all":"",
                "country_all":"1",
            },
            {
                "manager": "",
                "addTime": "2023-12-01 11:04:32",
                "subs": [
                    {
                        "isDefaultAuth": 0,
                        "uId": 75004,
                        "jobId": "GRT00003",
                        "name": "测试03",
                        "jobIdName": "GRT00003(测试03)",
                        "isDepManager": 1,
                        "orgId": 42,
                    },
                    {
                        "isDefaultAuth": 0,
                        "uId": 75002,
                        "jobId": "GRT00001",
                        "name": "测试0001",
                        "jobIdName": "GRT00001(测试0001)",
                        "isDepManager": 0,
                        "orgId": 42,
                    },
                    {
                        "isDefaultAuth": 0,
                        "uId": 75003,
                        "jobId": "GRT00002",
                        "name": "测试02",
                        "jobIdName": "GRT00002(测试02)",
                        "isDepManager": 0,
                        "orgId": 42,
                    }
                ],
                "level": "一级部门",
                "parentIds": "41-42-",
                "addJob": "GRT26227(柯柯)",
                "updateTime": "2023-12-01 11:15:33",
                "type": 10,
                "parentId": 41,
                "companyId": 41,
                "name": "国际客服中心",
                "id": 42,
                "orgNums": 3,
                "managers": "GRT00003(测试03)",
                "status": 1,
                "area_all":"",
                "country_all":"1",
            }
        ],
        "level": "总公司",
        "parentIds": "41-",
        "addJob": "GRT00000(杜永镇)",
        "updateTime": "",
        "type": 0,
        "parentId": 0,
        "companyId": 41,
        "name": "深圳古瑞瓦特",
        "id": 41,
        "orgNums": 0,
        "managers": "",
        "status": 1
    }
];